# Generated by Django 4.1.3 on 2022-11-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('restrictions', models.CharField(choices=[('N', 'None'), ('D', 'Dairy-Free'), ('G', 'Gluten-Free'), ('L', 'Lactose-Free'), ('N', 'Nut-Free'), ('S', 'Soy-Free'), ('V', 'Vegan')], default='N', max_length=1)),
                ('url', models.URLField()),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dessert')),
            ],
        ),
    ]
