# Generated by Django 4.1.3 on 2022-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='restrictions',
            field=models.CharField(choices=[('N', 'None'), ('D', 'Dairy-Free'), ('G', 'Gluten-Free'), ('L', 'Lactose-Free'), ('N', 'Nut-Free'), ('S', 'Soy-Free'), ('V', 'Vegan')], default='N', max_length=1, verbose_name='Dietary Restrictions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(verbose_name='Link to Recipe'),
        ),
    ]
