# Generated by Django 4.1.3 on 2022-11-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='spots',
            field=models.ManyToManyField(to='main_app.spot'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='zipcode',
            field=models.IntegerField(verbose_name='Zip'),
        ),
    ]
