# Generated by Django 4.1.3 on 2022-11-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_dessert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='category',
            field=models.CharField(choices=[('B', 'Baked'), ('D', 'Drink'), ('F', 'Frozen'), ('N', 'No-Bake'), ('O', 'Other')], default='B', max_length=1),
        ),
    ]
